# Generated by Django 5.1.1 on 2024-10-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(max_length=100, unique=True, verbose_name='userID'),
        ),
    ]
